[branding]
name = "Vleer (Official)"
email = "contact@vleer.app"
short = "VLEER"
logo = "https://openmusic.vleer.app/logo.png"
theme = "#ff6600"

[branding.links]
homepage = "https://openmusic.vleer.app"
privacy_statement = "https://openmusic.vleer.app/privacy"

[details]
version = "1.2.3"

[details.capabilities]
artists = true

[server]
secret = "123"
