[branding]
name = "Vleer (Official)"
email = "contact@vleer.app"
short = "VLEER"
logo = "https://docs.vleer.app/openmusic.svg"
theme = "#ff6600"

[branding.links]
homepage = "https://docs.vleer.app/openmusic"
privacy_statement = "https://docs.vleer.app/privacy"

[details]
version = "1.2.3"

[details.capabilities]
artists = true

[server]
secret = "123"
music_path = "./music"
